---
# Default values for http-https-echo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:  mendhak/http-https-echo
  tag: 30
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 8080
  httpsPort: 8443